
Vagrant.configure(2) do |config|

  #Base box name
  config.vm.box = "box-cutter/ubuntu1404-desktop"

  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
  	vb.gui = true
  #   # Customize the amount of memory on the VM:
  	vb.memory = "2048"
  	vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  	vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
  end

  #Script to provision virtual machine
  config.vm.provision :shell, path: "bootstrap.sh"
end
